services:

  # mongo-db:
  #   image: mongo:6.0.6
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongo-user
  #     MONGO_INITDB_ROOT_PASSWORD: 123456
  #   volumes:
  #     - ./mongo:/data/db
  #   ports:
  #     - 27017:27017

  postgres-db:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: my-db
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - postgres-db